UIDATIMP-65: Increase test coverage for FindImportProfile component
folio-org/ui-plugin-find-import-profile pull request #150
Opened 2024-01-04 12:26 UTC by OleksandrHladchenko1

## Links
[UIPFIMP-65](https://issues.folio.org/browse/UIPFIMP-65)

### Before
![image](https://github.com/folio-org/ui-plugin-find-import-profile/assets/85172747/39c6fded-b73c-4b94-a461-98f70574f17c)

### After
![image](https://github.com/folio-org/ui-plugin-find-import-profile/assets/85172747/00089e13-2f7e-4f1a-abf4-06774440cfd0)

2024-01-04 12:49 UTC, Terala-Priyanka requested changes
Could import both the named imports on the same line? It fixes the lint errors.

2024-01-05 12:02 UTC, mariia-aloshyna approved these changes

2024-01-05 12:04 UTC, mariia-aloshyna commented
Jira ticket to clean up eslint errors - [UIPFIMP-68](https://issues.folio.org/browse/UIPFIMP-68)

2024-01-05 17:15 UTC, Terala-Priyanka approved these changes
There are lint errors of same type in other files that you have not changed. Please correct them as well. It would hardly consume a minute of your time.

2024-01-08 09:09 UTC, merged